# Generated by Django 5.1.7 on 2025-10-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dean_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='teacher_post',
        ),
        migrations.AlterField(
            model_name='practice',
            name='students',
            field=models.ManyToManyField(related_name='studentes', to='univer.student'),
        ),
    ]
