# Generated by Django 5.1.7 on 2025-10-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0002_remove_post_dean_post_remove_post_teacher_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lecture',
            field=models.ManyToManyField(related_name='schulde1', to='univer.lectures'),
        ),
    ]
