# Generated by Django 5.2.6 on 2025-09-12 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('is_teacher', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('teacher_type', models.CharField(choices=[('Lector', 'lector'), ('Practicant', 'practicant')], default='Lector', max_length=50)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dean', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='univer.dean')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultyLess', to='univer.faculty')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='univer.teacher')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.IntegerField()),
                ('type_of_student', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhDstudent', 'phdstudent')], max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultyies', to='univer.faculty')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('08:00-08:50', '08:00 - 08:50'), ('09:00-09:50', '09:00 - 09:50'), ('10:00-10:50', '10:00 - 10:50'), ('11:00-11:50', '11:00 - 11:50'), ('12:00-12:50', '12:00 - 12:50'), ('13:00-13:50', '13:00 - 13:50'), ('14:00-14:50', '14:00 - 14:50'), ('15:00-15:50', '15:00 - 15:50'), ('16:00-16:50', '16:00 - 16:50'), ('17:00-17:50', '17:00 - 17:50'), ('18:00-18:50', '18:00 - 18:50'), ('19:00-19:50', '19:00 - 19:50'), ('20:00-20:50', '20:00 - 20:50')], max_length=50)),
                ('room', models.IntegerField()),
                ('lesson_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='univer.lessons')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_practice', to='univer.teacher')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Practice',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author_type', models.CharField(choices=[('teacher', 'Teacher'), ('dean', 'Dean')], max_length=155)),
                ('dean_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dean_posts', to='univer.dean')),
                ('teacher_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='univer.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('08:00-08:50', '08:00 - 08:50'), ('09:00-09:50', '09:00 - 09:50'), ('10:00-10:50', '10:00 - 10:50'), ('11:00-11:50', '11:00 - 11:50'), ('12:00-12:50', '12:00 - 12:50'), ('13:00-13:50', '13:00 - 13:50'), ('14:00-14:50', '14:00 - 14:50'), ('15:00-15:50', '15:00 - 15:50'), ('16:00-16:50', '16:00 - 16:50'), ('17:00-17:50', '17:00 - 17:50'), ('18:00-18:50', '18:00 - 18:50'), ('19:00-19:50', '19:00 - 19:50'), ('20:00-20:50', '20:00 - 20:50')], max_length=50)),
                ('room', models.IntegerField()),
                ('lessons_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_name', to='univer.lessons')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='univer.teacher')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Lectures',
            },
        ),
    ]
