# Generated by Django 5.1.7 on 2025-10-05 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0002_remove_student_course_alter_lectures_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='students',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='univer.student'),
            preserve_default=False,
        ),
    ]
