# Generated by Django 5.1.7 on 2025-10-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0003_practice_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='students',
        ),
        migrations.AddField(
            model_name='practice',
            name='students',
            field=models.ManyToManyField(related_name='student', to='univer.student'),
        ),
    ]
