# Generated by Django 5.1.7 on 2025-10-06 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0004_remove_practice_students_practice_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='students',
            field=models.ManyToManyField(related_name='students', to='univer.student'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='univer.lectures')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='univer.practice')),
            ],
        ),
    ]
