# Generated by Django 5.1.7 on 2025-10-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0005_alter_practice_students_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.AddField(
            model_name='lectures',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default=2, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default=2, max_length=3),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='practice',
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecture',
            field=models.ManyToManyField(related_name='lecture', to='univer.lectures'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='practice',
            field=models.ManyToManyField(related_name='practice', to='univer.practice'),
        ),
    ]
